apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  labels:
    app: docker-test
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
      - name: docker-test
        image: jackops93/inspector_base:1.0.2
        ports:
        - containerPort: 8081
        volumeMounts:
          - name: docker
            mountPath: /var/run/
      volumes:
      - name: docker
        hostPath:
          path: /var/run/